### ISSUE TITLE
Bond-Length-Dependent Rattle `stdev`?

### ISSUE THREAD

**Issue by kavanase** [SMTG-UCL/ShakeNBreak#27]
Hey @ireaml!
Something I was thinking about again. I wonder if it would be best to choose the rattle `stdev` based off the bulk bond length. We already get `d_min` from the bulk bond length, so easy to implement. I know this was briefly discussed before but I can’t really remember why we decided against it :sweat_smile: 
I know one of the issues was that the cases where some defects would consistently return energies higher than unperturbed (due to the supercell being stuck in a higher-energy rattled local minimum) didn’t have a clear correlation as to when it would/wouldn't happen, with it often only occurring for one or two specific defects in specific charge states.

From testing more on a range of compounds here in 🇯🇵, it seems there is definitely a correlation with the bulk bond length, though no clear cutoff or anything. Here I'm plotting the distributions of the bulk bond lengths of oxides I've ran `SnB` on, for the oxygen vacancies, and coloured orange for any that had a defect species where this occurred.
- _I would note here that this was a very rare occurrence (recent updates to setting `d_min` I think have def helped this), happened in <5% of defects and this is for oxides (which we know are the most likely for this to occur due to the strong ionic bonding), without adjusting the default rattle `stdev` of 0.25 Å_.

From the two datasets (19 and 33 compounds each), you can see there definitely is a trend with this being more likely for the compounds with lower bond lengths:
![image](https://user-images.githubusercontent.com/51478689/198234278-5fac11cf-dd98-4b2f-aed3-8bf5f703c046.png)
![image](https://user-images.githubusercontent.com/51478689/198234310-6760e30c-5b42-47e7-8c04-67489b010b4d.png)
![image](https://user-images.githubusercontent.com/51478689/198234336-9bb7710f-558a-44f7-9c04-6c445be926f7.png)
![image](https://user-images.githubusercontent.com/51478689/198234351-8b2fbcc3-e6b1-4c34-8758-0613421d274d.png)

I know from tests before, we typically found the larger the rattle `stdev` the better for performance, but I think the effect was typically relatively small, with the key effect of rattling being to break symmetry and disrupt the lattice potential. So do you think it would make sense to set the rattle `stdev` based on the bulk bond length? Maybe something like 7.5% or 10%?
For comparison we know CdTe and Sb2Se3 were all fine with 0.25 Å, which is around 8.8% and 9.2% each, and I think Sb2S3 didn't have this issue either right? (0.25 Å would be 10% for it). But TiO2 (for which 0.25 Å would be 13%) needed to have it reduced for some cases I think?

If so, I'll rerun each of the cases where this occurred with the rattle `stdev`s set to 7.5% and 10% of the bulk bond length, and see how they get on! Will also test this choice on the cases I have with GGA that found energy-lowering distortions, and see if using this choice still finds the groundstate

**Comment by ireaml** [comment]
Hi Seán!
You're right, I remember that 8/10% `stdev` was often fine, and think we recommended it in the inital version of the `Example Notebook` for compounds with strong ionic bonding or short distances.  Sb2S3 was fine but think there was an issue with GaAs (where 0.25 Å would be 9.8%)

From that data, I think it def makes sense to rerun a few cases to sanity check they are fine with smaller `stdev` and if so, refactor it to 7.5%/10% as you say :)

**Comment by kavanase** [comment]
Ok cool! Will keep you posted!

**Comment by kavanase** [comment]
Hey @ireaml, results are in!
So for the 14 specific vacancies I found for this to occur (from around 300), each now ran fine with no consistent 'stuck-rattle' high energies, using `stdev`s equal to 7.5% and 10% of the bulk bond length, except for one of the two inequivalent vacancies in Na5NbO5 in the +2 charge state. 
The 7.5% and 10% bond length rattles for this still give a `Rattled` structure 0.16 eV higher in energy. I reran this one with 2.5% and 5% rattles (0.0475 Å and 0.095  Å respectively), and these run fine, and actually find a much lower energy structure. Here I've renamed these folders to `Rattled_from_stdev_0_X` where `X` = `025`, `05`, `075` and `1` for the different `stdev` percentages, to use `snb-plot` to show together:
<img width="993" alt="image" src="https://user-images.githubusercontent.com/51478689/198936953-db90fecf-0fae-4fe4-99ba-d1a757d14c2b.png">

For the other cases that all now ran fine with the bond-length dependent rattles, 7 of the 14 give all distortions at same energy as unperturbed. For the other 6 however, they actually reveal an energy-lowering distortion which was previously missed due to the high-energy stuck-rattle results. E.g. for SrGa2B2O7, +2 vacancy in three inequivalent sites:
<img width="934" alt="image" src="https://user-images.githubusercontent.com/51478689/198933124-dd2ce300-22bb-438f-9c51-7695d482c8c2.png">
<img width="933" alt="image" src="https://user-images.githubusercontent.com/51478689/198933741-bd4836ec-0950-4e70-a839-313eaa9a1d9c.png">
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/51478689/198937599-cc73ec5c-a9fb-4524-9054-b7a22af5cf32.png">

Comparing the 7.5% and 10% rattles, we find better performance for the 10% rattle:
- The `Va_O1_2` 1.3 eV energy lowering distortion above for SrGa2B2O7 was only found with 10% and not 7.5% rattle.
- For `Va_O1_2` in Li5BiO5, we find a slightly lower structure with the 10% rattle that isn't found with 7.5% rattle (though in this case the difference is only 25 meV so not too significant):
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/51478689/198938112-35879be3-9f4a-4ec0-bab0-4e6cf024b416.png">
- For Zr(MoO4) +1 vacancy, the reduced `stdev` ends up finding a significantly lower energy structure (ΔE = -0.85 eV). Here the 7.5% rattle actually outperforms the 10% rattle, finding more lower energy structures, though they both only find the actual groundstate for two datapoints:
<img width="2316" alt="image" src="https://user-images.githubusercontent.com/51478689/198938457-20f4e6a8-c64c-443b-a280-38b3129a3439.png">

- The neutral and +2 charge state of this vacancy also found energy-lowering distortions (and ran fine) with the default 0.25 Å `stdev`, and when imported and tested for the +1 charge state both of those structures give a lower energy structure at ΔE = -0.7 eV (which corresponds to the slightly higher low-energy datapoints in that plot above – but not the actual groundstate):
- <img width="912" alt="image" src="https://user-images.githubusercontent.com/51478689/198932796-944e7b9f-32c5-459e-8d43-0a03986d790f.png">
- <img width="894" alt="image" src="https://user-images.githubusercontent.com/51478689/198932881-695f2f19-ade6-485d-b0e0-8af6c1725a33.png">

- I also accidentally reran this +1 vacancy for SrGa2B2O7, and found that the 7.5% rattle gave the groundstate for 3 datapoints, and the original 0.25 Å (equivalent to 19% rattle) gave it for 4 datapoints:
<img width="936" alt="image" src="https://user-images.githubusercontent.com/51478689/198933776-273f635b-0645-4c2f-9096-fa6a1d7e720a.png">
as well as 4 datapoints for the 10% rattle:
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/51478689/198937693-45a0a70f-9eb5-403d-980c-7b35cb4a6145.png">

So overall these observations do agree with our current understanding that, in general but not always, larger rattles are slightly more likely to find the groundstate. I think from these observations a 10% bond length rattle `stdev` would be good to use. It matches well with the rattle `stdev`s we previously used for CdTe and Sb2Se3, and here is shown to avoid the high energy 'stuck rattle' occurrence in >90% of the cases where it happened for the oxides, while giving good performance in finding groundstates (finding several which were missed in the first place because of this issue). If you agree I'll add this to `develop`, and update our tips in the docs about this!

**Comment by kavanase** [comment]
So from these results and the issue you mentioned with GaAs with a 9.8% rattle, it means 10% isn't perfect in all cases, but seems to be better performance-wise and more generally-applicable than just a flat value of 0.25 Å

**Comment by ireaml** [comment]
Nice results! Very cool that the 10% bond length rattle `stdev` avoids getting stuck and finds lower energy structures previously missed with the 0.25 A  `stdev`! 
I think everything sounds good!

Something else that pop to mind while reading your comment: do you think it could be worthy to test using different rattle `seeds` for different distortion factors (e.g. bond distortion of -50% and seed of 42, bond distortion of -30% and seed of 20 etc, so each distortion has a slight different rattle)? Might help the cases where a particular rattle gets stuck in a local minimum? Of course, with the 10% bond length rattle `stdev` this is now very uncommon, so might not be worthy?

**Comment by kavanase** [comment]
I think that's a great idea! And easy to implement. 
I think it would be best to have a consistent, reproducible logic with how the seed values are chosen, so that the same e.g. `snb-generate` command will give the same output structures unless the user specifically changes a parameter, to ensure easy reproducibility of generated structures and results. So maybe setting seed equal to the rounded integer value of the distortion factor *100 would make sense then?
E.g. seed = 40 for -60%, seed = 160 for +60% etc

**Comment by ireaml** [comment]
Yup, that's a good logic!
I guess we could add an optional parameter (like `same_seed` or a better name) to use the same rattle seed, for compatibility with older versions and current tests?

**Comment by kavanase** [comment]
Yeah was thinking about the backwards consistency too... For using the same seed, I guess just having seed as a kwarg (the way it currently is I think) works for this? So specifying seed with apply_distortions() or in a config file for snb-generate will mean that same seed is used for each? So could use this with the tests (but ofc adding a test to check the expected default behaviour), and note in the changelog (and keeping in mind if anyone says they want to retroactively generate previous structures) that people can set seed to 42 to get the previous default behaviour? 

The rattling procedure has already been updated quite a bit at several points in the last year (using MC rattle, setting d_min, using a bond-length dependent d_min etc), so already our rattling isn't fully backwards consistent (but in a good way, cause we know the updated methods perform better)

**Comment by ireaml** [comment]
Yeah you're right!

**Comment by kavanase** [comment]
Ok cool! Will implement asap! 😃

**Comment by kavanase** [comment]
Now implemented in commits aeddcb245b918ea23c838ea468daec569060a2e6 to 777ecd265e68da89032f99fd9ad1aec8461414ee 🎉 🎉 
I think this is a nice enhancement to the code!
