### ISSUE TITLE
Question about Structure Generation 

### ISSUE THREAD

**Issue by tommyxuecong** [SMTG-UCL/ShakeNBreak#47]
greetings! It's Xuecong here and I used the command in 'For a single defect' part of 'Structure Generation'  to generate the intrinsic defect of my Cr2O3 calculation. 
snb-generate --bulk POSCAR_hex_120.vasp --defect POSCAR
(here .vasp is my 120 symmetry origin bulk and POSCAR has a manully added O interstitial atom)
However I find out that the atom relative far from the defect cell(O1) are shifted even further tham the atom around my defect. Could you help with this problem? Many thanks
following is the POSCAR_hex_120.vasp and POACAR
[input.txt](https://github.com/SMTG-UCL/ShakeNBreak/files/11217837/input.txt)

**Comment by tommyxuecong** [comment]
0.0%__num_neighbours=2__O_i_m1
1.0
   9.9335107803000007    0.0000000000000000    0.0000000000000000
  -4.9667553902000003    8.6026726844999999    0.0000000000000000
   0.0000000000000000    0.0000000000000000   13.6472196578999991
Cr O
48 73
direct
   0.0175793736591610    0.0226079235405577    0.1505798660576018 Cr3+
   0.0181868096511504    0.5307381442368010    0.1505988639132231 Cr3+
   0.4901366567537038    0.0061331845696370    0.1420243305040593 Cr3+
   0.5071377985955432    0.4551007445040895    0.1708996761845783 Cr3+
   0.3475995365775826    0.1837021016398377    0.4679662578492303 Cr3+
   0.3370951911330565    0.6843362198404801    0.4647483040275970 Cr3+
   0.8103793539248659    0.1407397973056106    0.4801902001468273 Cr3+
   0.8308536982963173    0.6589027614939971    0.4778145947385462 Cr3+
   0.1739193204994384    0.3356022153636740    0.7925682409019088 Cr3+
   0.1610453629809410    0.8066186947163795    0.8101684747386716 Cr3+
   0.6360537582241842    0.3046781285457179    0.8265101444616336 Cr3+
   0.6641163141799538    0.8371940311039382    0.8101324021195838 Cr3+
   0.0159238013078150    0.0068586081151507    0.8466805465861674 Cr3+
  -0.0101408358064733    0.4941011530373731    0.8537880079382755 Cr3+
   0.5182350791793245   -0.0143554182134740    0.8333655346914620 Cr3+
   0.5042567364013688    0.4914439959208242    0.8664929531429415 Cr3+
   0.3511335693488162    0.1756489531919682    0.1789547578681557 Cr3+
   0.3426743332157887    0.6435023373935196    0.1760340288406046 Cr3+
   0.8198132228090156    0.1750287782089198    0.2002217187680644 Cr3+
   0.8017014033533951    0.6696187052559608    0.1601623067761371 Cr3+
   0.1905609610806743    0.3430784962898810    0.5274099010355101 Cr3+
   0.1577024322117767    0.8430450624413296    0.5216055474489391 Cr3+
   0.6498512896128351    0.3245365248603194    0.4968012980858917 Cr3+
   0.6904918449182975    0.8273041253487018    0.4945160673833341 Cr3+
   0.0429516827449365    0.0234511130139215    0.3350331151753111 Cr3+
   0.0158391540623641    0.5391713324995605    0.3556787989231709 Cr3+
   0.5101481213812175    0.0128089244617422    0.3438612643527282 Cr3+
   0.5052984633090479    0.5147316922574460    0.3648252780120548 Cr3+
   0.3283285168702956    0.1605069980284356    0.6828233102319854 Cr3+
   0.3396598497926504    0.6625867954490111    0.6938323317198748 Cr3+
   0.8410548878384217    0.1945166700262437    0.7053827234982417 Cr3+
   0.8148543186042403    0.7050035732454917    0.6540846182729929 Cr3+
   0.1471907358322693    0.2863340371137371   -0.0010494720078729 Cr3+
   0.1368439559977089    0.8437817912531110    0.0190795688813886 Cr3+
   0.6679036976744205    0.3764686607430719    0.0104633606751797 Cr3+
   0.6970154294234138    0.8805188687893617    0.0055873821319332 Cr3+
   0.0010746673357315   -0.0012576423033983    0.6569344411981674 Cr3+
   0.0030570751708845    0.4823655663859422    0.6607141034223803 Cr3+
   0.5100663387684250    0.0012368986791587    0.6539357294032936 Cr3+
   0.5158256245853434    0.4784817134822711    0.6762665080716649 Cr3+
   0.3403729438861109    0.1736148740776368    0.9941099341253722 Cr3+
   0.3301274009116111    0.6923904910052163    0.9873234174954705 Cr3+
   0.8315750815310884    0.1699997007347107    0.9809562186782887 Cr3+
   0.8521660585863772    0.7084881724186216    0.9898826275721914 Cr3+
   0.1683991405717932    0.3076220254154849    0.3034729539326327 Cr3+
   0.1478387699693863    0.8464599174539852    0.3201402909221128 Cr3+
   0.6786682051820931    0.3520854114111038    0.3329686209833440 Cr3+
   0.6676931672305486    0.8151729465643336    0.3314735405591919 Cr3+
   0.3333333330000000    0.1666666670000000    0.3335399999999999 O2-
   0.1348979431381768    0.4754948447769254    0.4086438006423761 O2-
   0.1666688006052892    0.9860861285901260    0.4166656178552241 O2-
   0.6715300388573154    0.5217787226593484    0.4321637500833498 O2-
   0.6856827412624988    1.0065590998771001    0.3901587313902852 O2-
  -0.0110644151716905    0.1368499653335669    0.7583091439375907 O2-
  -0.0217994269016391    0.6229990879473529    0.7308235336408924 O2-
   0.5102832413339775    0.1241588441791691    0.7620380923931953 O2-
   0.5082046335587839    0.6742131305159241    0.7139160451702015 O2-
   0.3167132274213545    0.3208402607807971    0.0924936236711339 O2-
   0.3295250329935717    0.8318460131602863    0.0947394511315787 O2-
   0.8437112772042082    0.3072314279294377    0.0825232223839367 O2-
   0.8599888517846638    0.8349455572974499    0.0957540745398803 O2-
   0.3553584195252850    0.0042366125578088    0.5829309628132203 O2-
   0.3080600884976400    0.4767558024414453    0.6045073398308080 O2-
   0.8655260976116537    0.0278382611752082    0.5835466693337580 O2-
   0.8378960998856874    0.5034795941454819    0.6010592073619377 O2-
   0.1888032061693985    0.1908191233339269    0.9067387255906879 O2-
   0.1933347705434142    0.6936483005299171    0.9158834110425100 O2-
   0.6494438669518119    0.1752315937802578    0.9146942526163753 O2-
   0.6453399308607000    0.6834017143005212    0.9137828818552779 O2-
   0.0245513613897392    0.3457371876838820    0.2655762553628955 O2-
   0.0132681321586908    0.8649125705691960    0.2385843415372495 O2-
   0.5065651057870469    0.3298597751954214    0.2558602392223570 O2-
   0.5331225486553546    0.8726312512422395    0.2321970401807538 O2-
   0.0201786885066284    0.2090343994481440    0.3984319082036091 O2-
  -0.0110404879972454    0.6495840337274824    0.4310404190703344 O2-
   0.5139138710912864    0.1805826719906251    0.4166656177085705 O2-
   0.5063677879649666    0.6820555864589438    0.4197119786871068 O2-
   0.3289654599285213    0.3398179124924658    0.7344233822604995 O2-
   0.3407661081600283    0.8705769517211277    0.7354426211350070 O2-
   0.8163954820625726    0.3257084763357317    0.7236199259999659 O2-
   0.8510407607582279    0.8964614075098447    0.7519386417649810 O2-
   0.2000833416456342    0.0387178138234483    0.0744281934201984 O2-
   0.1470398236618452    0.4843402786967658    0.0876500750702921 O2-
   0.6787383358320463    0.0226519771037228    0.1014677528664873 O2-
   0.7011852963061418    0.5336474788289122    0.0727578919096160 O2-
   0.5029036174151402    0.3530660269463070    0.5824919255311818 O2-
   0.4668004039477887    0.8118748366938795    0.5645075558555623 O2-
   1.0015001353773341    0.3294387616155508    0.5770003184419326 O2-
   0.9676151492889649    0.7961672290909670    0.5867043185358992 O2-
   0.3200646836866852    0.5057462014079362    0.9217290967295569 O2-
   0.2891299714686418    0.9669423421314262    0.8993854816988132 O2-
   0.7875919395075042    0.4634802234642245    0.9129718240740706 O2-
   0.8450331092029770    0.9874115692936335    0.9218266443244310 O2-
   0.1423001601051089    0.1381233220595098    0.2533476949996847 O2-
   0.1374407189995499    0.6621265557978400    0.2407738010581991 O2-
   0.6741676602022169    0.1513648231177059    0.2693789411248170 O2-
   0.6679116877718737    0.6635273396378691    0.2571013831510255 O2-
   0.3070410879531666    0.3249705485576289    0.4221725508600343 O2-
   0.3061646230412896    0.8665773540838624    0.4538834609581686 O2-
   0.8170374726514454    0.3365506459191765    0.4147265166144278 O2-
   0.8496665161802404    0.8858254529406899    0.4174675681941727 O2-
   0.1321746772107178   -0.0099388305421410    0.7408038509103143 O2-
   0.1481760909527538    0.5003108354169942    0.7653503074786188 O2-
   0.6428125008822720    0.0024421854471439    0.7389777487933243 O2-
   0.6492889431383770    0.4868969411070420    0.7466351359982587 O2-
   0.4610206621287083    0.1479833880042599    0.1018918577111325 O2-
   0.4668038627872561    0.6389618245088335    0.0842003856351239 O2-
   0.9590316438136255    0.1294959836456524    0.0658810432879964 O2-
   0.9572055423386463    0.6484831859690945    0.0698796957429175 O2-
   0.1968812344278916    0.1647253357818554    0.5935710556842375 O2-
   0.2043211832391424    0.6829749274140257    0.5681469614598327 O2-
   0.6520882330846738    0.1212160070263097    0.5760926672063081 O2-
   0.6389088560570368    0.6581387216634030    0.5573483780237148 O2-
   0.0071395156304338    0.3466825091563869    0.9107499004925154 O2-
   0.0070113546464244    0.8291174000403718    0.9149932015350460 O2-
   0.4892719612009873    0.3101289372026459    0.9236999862257231 O2-
   0.5048983727349416    0.8252409219835256    0.9330248145900135 O2-
   0.3494927753163093   -0.0231989919814478    0.2456484908749234 O2-
   0.3901910233530433    0.5096770923395237    0.2451146687393771 O2-
   0.8767498466429758   -0.0254090715610972    0.2631250183971229 O2-
   0.8315302640919975    0.4861618227564249    0.2493173425227271 O2-

**Comment by kavanase** [comment]
Hi @tommyxuecong! 
We're going to close this issue now. Feel free to reopen it or ask any other questions if you're running into trouble! 😃
