### ISSUE TITLE
Package Development

### ISSUE THREAD

**Issue by kavanase** [SMTG-UCL/ShakeNBreak#5]
This is an Issue to track the development of this package, to have it ready for JOSS submission.

Key tasks and the best order of operation (as I see it):
- [X] Docstrings for each function (completed with 982e70882c09b6659e342a751d1687715c7696bc)
- [X] Set up GitHub Actions to auto-run the tests when a new push is made.
- [x] Re-modularise. Once the tests and docstrings are in place, we should think about the best module structure for the package, and re-organise the scripts a bit.
- [x] Examples. The current example notebook is a great template, and the test data can also be used for this.
- [X] Tests for the key functions in each module. Currently have this for the `distortions.py`, `input.py`, `energy_lowering_distortions.py`, `analysis.py`, `plotting.py`, `io.py` and `cli.py` scripts. Most tests now written, just need final scan to check full coverage.
- [x] Feature addition (#3, #4 and any other key features we decide are necessary)
- [x] Documentation (i.e. a docs site). Should be relatively straightforward to generate now that the docstrings are in order, as can be generated from these with just some extra info.

Of course suggestions on this welcome!

**Comment by ireaml** [comment]
As an initial version of the docs site is now live (https://shakenbreak.readthedocs.io/en/latest/index.html), will close this issue :balloon:
