### ISSUE TITLE
Folder Structure

### ISSUE THREAD

**Issue by kavanase** [SMTG-UCL/ShakeNBreak#9]
The current folder structure generated by `ShakeNBreak` is `defect_name`/`distortion_type`/`defect_name`_`distortion_key`/`vasp_gam`. The structure makes sense, but I think it might be a little clunky / offputting for users. 
The `vasp_gam` part is a legacy effect from the `doped` `vasp_gam_files` function, but I think isn't necessary as the user knows these are `vasp_gam` distortion test runs (from the upper folder structure, and likely they're running the distortion tests in a separate directory to final production run defects anyway). Can be factored out when modifying the VASP I/O parts.
The `distortion_type` which is either `BDM` or `champion` I think can be removed, as again the user should know these are distortion tests from the `-XX%_` labels in the `distortion_key`s etc. For the `champion` runs, I think these could be made to run in the same `defect_name` folder as the distortions, just with an obvious different name (like `defect_name_champion`?)

So suggesting that our default folder structure is changed to: `defect_name`/`defect_name`_`distortion_key` to make it more succinct. What do you think @ireaml?

**Comment by ireaml** [comment]
Agree!

**Comment by ireaml** [comment]
Also, from the `distortion_key` think we could remove `Bond_Distortion` and update `Unperturbed_Defect` by `Unperturbed` only, to shorten a bit the names?

**Comment by kavanase** [comment]
Good suggestion! 
Thinking about it, I think we don't need to have `defect_name` in the subfolder names (as we already know what defect it is from the top-level folder). What about using `defect_name`/`distortion_key` instead of `defect_name`/`defect_name`_`distortion_key`, so e.g. `vac_1_Cd_0`/`-50.0%_Bond_Distortion`? In that case, might be better to keep `Bond_Distortion`, as `-50.0%` on it's own might be cutting too much in this case, so having some reminder to the user what the "`-50.0%`" actually refers to here (because we've also decided to cut the `BDM` folder). What do you think?

And yep using `Unperturbed` rather than `Unperturbed_Defect` is a good shout! Also means it matches with the `dict` and `DataFrame` outputs from `ShakeNBreak` as well.

**Comment by ireaml** [comment]
Yup think that's better!

**Comment by kavanase** [comment]
Closing now as this has been implemented in the linked commits by @ireaml and also 96eb9534173c7f6142e94c23bb894986de847f8e and 7857cc2497ff0d1470f5a6ca9a85cd120728e90c
